export const CONFIG = {

  URL_ROOT: "",

  CARD_CODE_LENGTH: 2,
  CARDS_IN_ROW: 5,
  ROWS: 5,

  PERSON: [
    {name: 'RZEŹNIK', image: '/sledztwo/assets/person/rzeznik.png'},
    {name: 'MALARZ', image: 'sledztwo/assets/person/malarz.png'},
    {name: 'BURMISTRZ', image: '/assets/person/burmistrz.png'},
    {name: 'POMOC DOMOWA', image: '/assets/person/pomoc_domowa.png'},
    {name: 'SPRZEDAWCA', image: '/assets/person/sprzedawca.png'},
    {name: 'LUNATYK', image: '/assets/person/lunatyk.png'},
    {name: 'PSYCHOTERAPEUTKA', image: '/assets/person/psychoterapeutka.png'},
    {name: 'TOP MODELKA', image: '/assets/person/top_modelka.png'},
    {name: 'OGRODNIK', image: '/assets/person/ogrodnik.png'},
    {name: 'KUCHARKA', image: '/assets/person/kucharka.png'},
    {name: 'KELNERKA', image: '/assets/person/kelnerka.png'},
    {name: 'TRENERKA', image: '/assets/person/trenerka.png'},
    {name: 'FARMACEUTKA', image: '/assets/person/farmaceutka.png'},
    {name: 'PISARZ', image: '/assets/person/pisarz.png'},
    {name: 'MECHANIK', image: '/assets/person/mechanik.png'},
    {name: 'NAUCZYCIELKA', image: '/assets/person/nauczycielka.png'},
    {name: 'KIEROWCA AUTOBUSU', image: '/assets/person/kierowca_autobusu.png'},
    {name: 'DIETETYCZKA', image: '/assets/person/dietetyczka.png'},
    {name: 'PACJENTKA', image: '/assets/person/pacjentka.png'},
    {name: 'TURYSTA', image: '/assets/person/turysta.png'},
    {name: 'DZIENNIKARKA ŚLEDCZA', image: '/assets/person/dziennikarka_sledcza.png'},
    {name: 'DOZORCA', image: '/assets/person/dozorca.png'},
    {name: 'SĘDZIA', image: '/assets/person/sedzia.png'},
    {name: 'DUCHOWNY', image: '/assets/person/duchowny.png'},
    {name: 'WETERYNARZ', image: '/assets/person/weterynarz.png'},
    {name: 'NASTOLATEK', image: '/assets/person/nastolatek.png'},
    {name: 'GEEK', image: '/assets/person/geek.png'},
    {name: 'ROWERZYSTKA', image: '/assets/person/rowerzystka.png'},
    {name: 'PIELĘGNIARKA', image: '/assets/person/pielegniarka.png'},
    {name: 'HYDRAULIK', image: '/assets/person/hydraulik.png'},
    {name: 'KIBIC PIŁKARSKI', image: '/assets/person/kibic_pilkarski.png'},
    {name: 'WŁAŚCICIEL NIERUCHOMOŚCI', image: '/assets/person/wlasciciel_nieruchomosci.png'},
    {name: 'KOLEŻANKA Z PRACY', image: '/assets/person/kolezanka_z_pracy.png'},
    {name: 'PRAWNICZKA', image: '/assets/person/prawniczka.png'},
    {name: 'LISTONOSZ', image: '/assets/person/listonosz.png'},
    {name: 'SĄSIAD', image: '/assets/person/sasiad.png'},
    {name: 'SZEFOWA GANGU', image: '/assets/person/szefowa_gangu.png'},
    {name: 'DZIKI LOKATOR', image: '/assets/person/dziki_lokator.png'},
    {name: 'PREZENTERKA', image: '/assets/person/prezenterka.png'},
    {name: 'RATOWNIK MEDYCZNY', image: '/assets/person/ratownik_medyczny.png'},
    {name: 'PREMIER', image: '/assets/person/premier.png'},
    {name: 'KSIĘGOWA', image: '/assets/person/ksiegowa.png'},
    {name: 'AKTOR', image: '/assets/person/aktor.png'},
    {name: 'PREZENTER POGODY', image: '/assets/person/prezenter_pogody.png'},
    {name: 'STUDENT', image: '/assets/person/student.png'},
    {name: 'OPIEKUNKA DO DZIECKA', image: '/assets/person/opiekunka_do_dziecka.png'},
    {name: 'ROLNIK', image: '/assets/person/rolnik.png'},
    {name: 'INTERNISTA', image: '/assets/person/internista.png'},
    {name: 'PROJEKTANT MODY', image: '/assets/person/projektant_mody.png'},
    {name: 'POLITYK', image: '/assets/person/polityk.png'},
    {name: 'SKRZYPACZKA', image: '/assets/person/skrzypaczka.png'},
    {name: 'EMERYTOWANY KOMISARZ POLICJI', image: '/assets/person/emerytowany_komisarz_policji.png'},
  ],

PLACE: [
    {name: 'PLAŻA', image: '/assets/place/plaza.png'},
    {name: 'RESTAURACJA', image: '/assets/place/restauracja.png'},
    {name: 'GALERIA SZTUKI', image: '/assets/place/galeria_sztuki.png'},
    {name: 'WINDA', image: '/assets/place/winda.png'},
    {name: 'ZAKŁAD FOTOGRAFICZNY', image: '/assets/place/zaklad_fotograficzny.png'},
    {name: 'BIBLIOTEKA', image: '/assets/place/biblioteka.png'},
    {name: 'CENTRUM MIASTA', image: '/assets/place/centrum_miasta.png'},
    {name: 'WYBIEG DLA MODELEK', image: '/assets/place/wybieg_dla_modelek.png'},
    {name: 'STACJA KOLEJOWA', image: '/assets/place/stacja_kolejowa.png'},
    {name: 'TOALETA PUBLICZNA', image: '/assets/place/toaleta_publiczna.png'},
    {name: 'POSTÓJ TAKSÓWEK', image: '/assets/place/postoj_taksowek.png'},
    {name: 'KLUB NOCNY', image: '/assets/place/klub_nocny.png'},
    {name: 'RÓW', image: '/assets/place/row.png'},
    {name: 'MAGAZYN', image: '/assets/place/magazyn.png'},
    {name: 'BAGNO', image: '/assets/place/bagno.png'},
    {name: 'SIEROCINIEC', image: '/assets/place/sierociniec.png'},
    {name: 'STRÓŻÓWKA', image: '/assets/place/strozowka.png'},
    {name: 'PRZEBIERALNIA NA SIŁOWNI', image: '/assets/place/przebieralnia_na_silowni.png'},
    {name: 'PARK MIEJSKI', image: '/assets/place/park_miejski.png'},
    {name: 'CMENTARZ', image: '/assets/place/cmentarz.png'},
    {name: 'PLAC BUDOWY', image: '/assets/place/plac_budowy.png'},
    {name: 'PRZYSTANEK AUTOBUSOWY', image: '/assets/place/przystanek_autobusowy.png'},
    {name: 'RZEŹNIA', image: '/assets/place/rzeznia.png'},
    {name: 'POLE GOLFOWE', image: '/assets/place/pole_golfowe.png'},
    {name: 'KINO', image: '/assets/place/kino.png'},
    {name: 'KOSTNICA', image: '/assets/place/kostnica.png'},
  ],

ITEM: [
    {name: 'BUTELKA SZAMPANA', image: '/assets/item/butelka_szampana.png'},
    {name: 'ROZBITE LUSTRO', image: '/assets/item/rozbite_lustro.png'},
    {name: 'MATERIAŁ FILMOWY', image: '/assets/item/material_filmowy.png'},
    {name: 'LATARKA', image: '/assets/item/latarka.png'},
    {name: 'MŁOTEK', image: '/assets/item/mlotek.png'},
    {name: 'RĘKAWICZKA', image: '/assets/item/rekawiczka.png'},
    {name: 'POCISK', image: '/assets/item/pocisk.png'},
    {name: 'KLUCZE', image: '/assets/item/klucze.png'},
    {name: 'ŁOM', image: '/assets/item/lom.png'},
    {name: 'STRZYKAWKA', image: '/assets/item/strzykawka.png'},
    {name: 'PORTFEL', image: '/assets/item/portfel.png'},
    {name: 'NIEDOPAŁEK', image: '/assets/item/niedopalek.png'},
    {name: 'TABLETKI', image: '/assets/item/tabletki.png'},
    {name: 'PILNICZEK DO PAZNOKCI', image: '/assets/item/pilniczek_do_paznokci.png'},
    {name: 'TRUCIZNA', image: '/assets/item/trucizna.png'},
    {name: 'BROŃ PALNA', image: '/assets/item/bron_palna.png'},
    {name: 'PASEK', image: '/assets/item/pasek.png'},
    {name: 'NÓŻ', image: '/assets/item/noz.png'},
    {name: 'TROFEUM', image: '/assets/item/trofeum.png'},
    {name: 'ZAŚNIEDZIAŁE MONETY', image: '/assets/item/zasniedziale_monety.png'},
    {name: 'ŻYLETKA', image: '/assets/item/zyletka.png'},
    {name: 'SZTUCZNA SZCZĘKA', image: '/assets/item/sztuczna_szczeka.png'},
    {name: 'LIST', image: '/assets/item/list.png'},
    {name: 'KAMIENIE SZLACHETNE', image: '/assets/item/kamienie_szlachetne.png'},
    {name: 'TELEFON KOMÓRKOWY', image: '/assets/item/telefon_komorkowy.png'},
    {name: 'SAMOCHÓD', image: '/assets/item/samochod.png'},
  ],

MOTIVE: [
    {name: 'NIEUDANA OPERACJA PLASTYCZNA', image: '/assets/motive/nieudana_operacja_plastyczna.png'},
    {name: 'UPUBLICZNIENIE PRYWATNYCH ZDJĘĆ', image: '/assets/motive/upublicznienie_prywatnych_zdjec.png'},
    {name: 'SAMOTNOŚĆ', image: '/assets/motive/samotnosc.png'},
    {name: 'SAMOOBRONA', image: '/assets/motive/samoobrona.png'},
    {name: 'ZDRADA', image: '/assets/motive/zdrada.png'},
    {name: 'ZNĘCANIE SIĘ', image: '/assets/motive/znecanie_sie.png'},
    {name: 'CIĄŻA', image: '/assets/motive/ciaza.png'},
    {name: 'UTRATA PRACY', image: '/assets/motive/utrata_pracy.png'},
    {name: 'ZBIEG OKOLICZNOŚCI', image: '/assets/motive/zbieg_okolicznosci.png'},
    {name: 'KRYZYS WIEKU ŚREDNIEGO', image: '/assets/motive/kryzys_wieku_sredniego.png'},
    {name: 'BIZNES NA BOKU', image: '/assets/motive/biznes_na_boku.png'},
    {name: 'ROMANS', image: '/assets/motive/romans.png'},
    {name: 'DŁUG', image: '/assets/motive/dlug.png'},
    {name: 'ZŁAMANE SERCE', image: '/assets/motive/zlamane_serce.png'},
    {name: 'KŁAMSTWO', image: '/assets/motive/klamstwo1.png'},
    {name: 'KŁAMSTWO', image: '/assets/motive/klamstwo2.png'},
    {name: 'SPADEK', image: '/assets/motive/spadek.png'},
    {name: 'PRANIE MÓZGU', image: '/assets/motive/pranie_mozgu.png'},
    {name: 'NIESPRAWIEDLIWOŚĆ', image: '/assets/motive/niesprawiedliwosc.png'},
    {name: 'ZEMSTA', image: '/assets/motive/zemsta.png'},
    {name: 'NARKOTYKI', image: '/assets/motive/narkotyki.png'},
    {name: 'PLOTKA', image: '/assets/motive/plotka.png'},
    {name: 'ZAZDROŚĆ', image: '/assets/motive/zazdrosc.png'},
    {name: 'TAJEMNICA Z PRZESZŁOŚCI', image: '/assets/motive/tajemnica_z_przeszlosci.png'},
    {name: 'UPRZEDZENIE', image: '/assets/motive/uprzedzenie.png'},
  ],
}