export const CONFIG = {

  URL_ROOT: "/sledztwo",

  CARD_CODE_LENGTH: 2,
  CARDS_IN_ROW: 5,
  ROWS: 5,

  PERSON: [
    {name: 'RZEŹNIK', image: '/assets/compressed/person/rzeznik.jpeg'},
    {name: 'MALARZ', image: '/assets/compressed/person/malarz.jpeg'},
    {name: 'BURMISTRZ', image: '/assets/compressed/person/burmistrz.jpeg'},
    {name: 'POMOC DOMOWA', image: '/assets/compressed/person/pomoc_domowa.jpeg'},
    {name: 'SPRZEDAWCA', image: '/assets/compressed/person/sprzedawca.jpeg'},
    {name: 'LUNATYK', image: '/assets/compressed/person/lunatyk.jpeg'},
    {name: 'PSYCHOTERAPEUTKA', image: '/assets/compressed/person/psychoterapeutka.jpeg'},
    {name: 'TOP MODELKA', image: '/assets/compressed/person/top_modelka.jpeg'},
    {name: 'OGRODNIK', image: '/assets/compressed/person/ogrodnik.jpeg'},
    {name: 'KUCHARKA', image: '/assets/compressed/person/kucharka.jpeg'},
    {name: 'KELNERKA', image: '/assets/compressed/person/kelnerka.jpeg'},
    {name: 'TRENERKA', image: '/assets/compressed/person/trenerka.jpeg'},
    {name: 'FARMACEUTKA', image: '/assets/compressed/person/farmaceutka.jpeg'},
    {name: 'PISARZ', image: '/assets/compressed/person/pisarz.jpeg'},
    {name: 'MECHANIK', image: '/assets/compressed/person/mechanik.jpeg'},
    {name: 'NAUCZYCIELKA', image: '/assets/compressed/person/nauczycielka.jpeg'},
    {name: 'KIEROWCA AUTOBUSU', image: '/assets/compressed/person/kierowca_autobusu.jpeg'},
    {name: 'DIETETYCZKA', image: '/assets/compressed/person/dietetyczka.jpeg'},
    {name: 'PACJENTKA', image: '/assets/compressed/person/pacjentka.jpeg'},
    {name: 'TURYSTA', image: '/assets/compressed/person/turysta.jpeg'},
    {name: 'DZIENNIKARKA ŚLEDCZA', image: '/assets/compressed/person/dziennikarka_sledcza.jpeg'},
    {name: 'DOZORCA', image: '/assets/compressed/person/dozorca.jpeg'},
    {name: 'SĘDZIA', image: '/assets/compressed/person/sedzia.jpeg'},
    {name: 'DUCHOWNY', image: '/assets/compressed/person/duchowny.jpeg'},
    {name: 'WETERYNARZ', image: '/assets/compressed/person/weterynarz.jpeg'},
    {name: 'NASTOLATEK', image: '/assets/compressed/person/nastolatek.jpeg'},
    {name: 'GEEK', image: '/assets/compressed/person/geek.jpeg'},
    {name: 'ROWERZYSTKA', image: '/assets/compressed/person/rowerzystka.jpeg'},
    {name: 'PIELĘGNIARKA', image: '/assets/compressed/person/pielegniarka.jpeg'},
    {name: 'HYDRAULIK', image: '/assets/compressed/person/hydraulik.jpeg'},
    {name: 'KIBIC PIŁKARSKI', image: '/assets/compressed/person/kibic_pilkarski.jpeg'},
    {name: 'WŁAŚCICIEL NIERUCHOMOŚCI', image: '/assets/compressed/person/wlasciciel_nieruchomosci.jpeg'},
    {name: 'KOLEŻANKA Z PRACY', image: '/assets/compressed/person/kolezanka_z_pracy.jpeg'},
    {name: 'PRAWNICZKA', image: '/assets/compressed/person/prawniczka.jpeg'},
    {name: 'LISTONOSZ', image: '/assets/compressed/person/listonosz.jpeg'},
    {name: 'SĄSIAD', image: '/assets/compressed/person/sasiad.jpeg'},
    {name: 'SZEFOWA GANGU', image: '/assets/compressed/person/szefowa_gangu.jpeg'},
    {name: 'DZIKI LOKATOR', image: '/assets/compressed/person/dziki_lokator.jpeg'},
    {name: 'PREZENTERKA', image: '/assets/compressed/person/prezenterka.jpeg'},
    {name: 'RATOWNIK MEDYCZNY', image: '/assets/compressed/person/ratownik_medyczny.jpeg'},
    {name: 'PREMIER', image: '/assets/compressed/person/premier.jpeg'},
    {name: 'KSIĘGOWA', image: '/assets/compressed/person/ksiegowa.jpeg'},
    {name: 'AKTOR', image: '/assets/compressed/person/aktor.jpeg'},
    {name: 'PREZENTER POGODY', image: '/assets/compressed/person/prezenter_pogody.jpeg'},
    {name: 'STUDENT', image: '/assets/compressed/person/student.jpeg'},
    {name: 'OPIEKUNKA DO DZIECKA', image: '/assets/compressed/person/opiekunka_do_dziecka.jpeg'},
    {name: 'ROLNIK', image: '/assets/compressed/person/rolnik.jpeg'},
    {name: 'INTERNISTA', image: '/assets/compressed/person/internista.jpeg'},
    {name: 'PROJEKTANT MODY', image: '/assets/compressed/person/projektant_mody.jpeg'},
    {name: 'POLITYK', image: '/assets/compressed/person/polityk.jpeg'},
    {name: 'SKRZYPACZKA', image: '/assets/compressed/person/skrzypaczka.jpeg'},
    {name: 'EMERYTOWANY KOMISARZ POLICJI', image: '/assets/compressed/person/emerytowany_komisarz_policji.jpeg'},
    {name: 'BARBER', image: '/assets/compressed/person/barber.jpeg'},
    {name: 'BARMANKA', image: '/assets/compressed/person/barmanka.jpeg'},
    {name: 'BOGATA CIOCIA', image: '/assets/compressed/person/bogata_ciocia.jpeg'},
    {name: 'BIZNESMEN', image: '/assets/compressed/person/biznesmen.jpeg'},
    {name: 'ĆPUN', image: '/assets/compressed/person/cpun.jpeg'},
    {name: 'IMIGRANT', image: '/assets/compressed/person/imigrant.jpeg'},
    {name: 'INFLUENCER', image: '/assets/compressed/person/influencer.jpeg'},
    {name: 'PIOSENKARZ', image: '/assets/compressed/person/piosenkarz.jpeg'},
    {name: 'INFORMATYK', image: '/assets/compressed/person/informatyk.jpeg'},
    {name: 'KOSMETYCZKA', image: '/assets/compressed/person/kosmetyczka.jpeg'},
    {name: 'KIEROWNIK BUDOWY', image: '/assets/compressed/person/kierownik_budowy.jpeg'},
    {name: 'ONLYFANSIARA', image: '/assets/compressed/person/onlyfansiara.jpeg'},
    {name: 'SPRZĄTACZKA', image: '/assets/compressed/person/sprzataczka.jpeg'},
    {name: 'STAŻYSTKA', image: '/assets/compressed/person/stazystka.jpeg'},
    {name: 'SYN MILIONERA', image: '/assets/compressed/person/syn_milionera.jpeg'},
  ],

PLACE: [
    {name: 'PLAŻA', image: '/assets/compressed/place/plaza.jpeg'},
    {name: 'RESTAURACJA', image: '/assets/compressed/place/restauracja.jpeg'},
    {name: 'GALERIA SZTUKI', image: '/assets/compressed/place/galeria_sztuki.jpeg'},
    {name: 'WINDA', image: '/assets/compressed/place/winda.jpeg'},
    {name: 'ZAKŁAD FOTOGRAFICZNY', image: '/assets/compressed/place/zaklad_fotograficzny.jpeg'},
    {name: 'BIBLIOTEKA', image: '/assets/compressed/place/biblioteka.jpeg'},
    {name: 'CENTRUM MIASTA', image: '/assets/compressed/place/centrum_miasta.jpeg'},
    {name: 'WYBIEG DLA MODELEK', image: '/assets/compressed/place/wybieg_dla_modelek.jpeg'},
    {name: 'STACJA KOLEJOWA', image: '/assets/compressed/place/stacja_kolejowa.jpeg'},
    {name: 'TOALETA PUBLICZNA', image: '/assets/compressed/place/toaleta_publiczna.jpeg'},
    {name: 'POSTÓJ TAKSÓWEK', image: '/assets/compressed/place/postoj_taksowek.jpeg'},
    {name: 'KLUB NOCNY', image: '/assets/compressed/place/klub_nocny.jpeg'},
    {name: 'RÓW', image: '/assets/compressed/place/row.jpeg'},
    {name: 'MAGAZYN', image: '/assets/compressed/place/magazyn.jpeg'},
    {name: 'BAGNO', image: '/assets/compressed/place/bagno.jpeg'},
    {name: 'SIEROCINIEC', image: '/assets/compressed/place/sierociniec.jpeg'},
    {name: 'STRÓŻÓWKA', image: '/assets/compressed/place/strozowka.jpeg'},
    {name: 'PRZEBIERALNIA NA SIŁOWNI', image: '/assets/compressed/place/przebieralnia_na_silowni.jpeg'},
    {name: 'PARK MIEJSKI', image: '/assets/compressed/place/park_miejski.jpeg'},
    {name: 'CMENTARZ', image: '/assets/compressed/place/cmentarz.jpeg'},
    {name: 'PLAC BUDOWY', image: '/assets/compressed/place/plac_budowy.jpeg'},
    {name: 'PRZYSTANEK AUTOBUSOWY', image: '/assets/compressed/place/przystanek_autobusowy.jpeg'},
    {name: 'RZEŹNIA', image: '/assets/compressed/place/rzeznia.jpeg'},
    {name: 'POLE GOLFOWE', image: '/assets/compressed/place/pole_golfowe.jpeg'},
    {name: 'KINO', image: '/assets/compressed/place/kino.jpeg'},
    {name: 'KOSTNICA', image: '/assets/compressed/place/kostnica.jpeg'},
    {name: 'BIURO', image: '/assets/compressed/place/biuro.jpeg'},
    {name: 'CIEMNY ZAUŁEK', image: '/assets/compressed/place/ciemny_zaulek.jpeg'},
    {name: 'LAS', image: '/assets/compressed/place/las.jpeg'},
    {name: 'METRO', image: '/assets/compressed/place/metro.jpeg'},
    {name: 'UCZELNIA', image: '/assets/compressed/place/uczelnia.jpeg'},
    {name: 'APTEKA', image: '/assets/compressed/place/apteka.jpeg'},
    {name: 'BANK', image: '/assets/compressed/place/bank.jpeg'},
    {name: 'BRZEG RZEKI', image: '/assets/compressed/place/brzeg_rzeki.jpeg'},
    {name: 'GARAŻ', image: '/assets/compressed/place/garaz.jpeg'},
    {name: 'HOTEL', image: '/assets/compressed/place/hotel.jpeg'},
    {name: 'JASKINIA', image: '/assets/compressed/place/jaskinia.jpeg'},
    {name: 'KASYNO', image: '/assets/compressed/place/kasyno.jpeg'},
    {name: 'KAWIARNIA', image: '/assets/compressed/place/kawiarnia.jpeg'},
    {name: 'KOMISARIAT POLICJI', image: '/assets/compressed/place/komisariat_policji.jpeg'},
    {name: 'KOŚCIÓŁ', image: '/assets/compressed/place/kosciol.jpeg'},
    {name: 'ŁAZIENKA', image: '/assets/compressed/place/lazienka.jpeg'},
    {name: 'LOTNISKO', image: '/assets/compressed/place/lotnisko.jpeg'},
    {name: 'MUZEUM', image: '/assets/compressed/place/muzeum.jpeg'},
    {name: 'PARKING PODZIEMNY', image: '/assets/compressed/place/parking_podziemny.jpeg'},
    {name: 'PIWNICA', image: '/assets/compressed/place/piwnica.jpeg'},
    {name: 'POLE KUKURYDZY', image: '/assets/compressed/place/pole_kukurydzy.jpeg'},
    {name: 'PORT', image: '/assets/compressed/place/port.jpeg'},
    {name: 'SALA OPERACYJNA', image: '/assets/compressed/place/sala_operacyjna.jpeg'},
    {name: 'SIŁOWNIA', image: '/assets/compressed/place/silownia.jpeg'},
    {name: 'SKLEP CAŁODOBOWY', image: '/assets/compressed/place/sklep_calodobowy.jpeg'},
    {name: 'STRYCH', image: '/assets/compressed/place/strych.jpeg'},
    {name: 'SYPIALNIA', image: '/assets/compressed/place/sypialnia.jpeg'},
    {name: 'SZLAK GÓRSKI', image: '/assets/compressed/place/szlak_gorski.jpeg'},
    {name: 'SZPITAL', image: '/assets/compressed/place/szpital.jpeg'},
    {name: 'WIĘZIENIE', image: '/assets/compressed/place/wiezienie.jpeg'},
  ],

ITEM: [
    {name: 'BUTELKA SZAMPANA', image: '/assets/compressed/item/butelka_szampana.jpeg'},
    {name: 'ROZBITE LUSTRO', image: '/assets/compressed/item/rozbite_lustro.jpeg'},
    {name: 'MATERIAŁ FILMOWY', image: '/assets/compressed/item/material_filmowy.jpeg'},
    {name: 'LATARKA', image: '/assets/compressed/item/latarka.jpeg'},
    {name: 'MŁOTEK', image: '/assets/compressed/item/mlotek.jpeg'},
    {name: 'RĘKAWICZKA', image: '/assets/compressed/item/rekawiczka.jpeg'},
    {name: 'POCISK', image: '/assets/compressed/item/pocisk.jpeg'},
    {name: 'KLUCZE', image: '/assets/compressed/item/klucze.jpeg'},
    {name: 'ŁOM', image: '/assets/compressed/item/lom.jpeg'},
    {name: 'STRZYKAWKA', image: '/assets/compressed/item/strzykawka.jpeg'},
    {name: 'PORTFEL', image: '/assets/compressed/item/portfel.jpeg'},
    {name: 'NIEDOPAŁEK', image: '/assets/compressed/item/niedopalek.jpeg'},
    {name: 'TABLETKI', image: '/assets/compressed/item/tabletki.jpeg'},
    {name: 'PILNICZEK DO PAZNOKCI', image: '/assets/compressed/item/pilniczek_do_paznokci.jpeg'},
    {name: 'TRUCIZNA', image: '/assets/compressed/item/trucizna.jpeg'},
    {name: 'BROŃ PALNA', image: '/assets/compressed/item/bron_palna.jpeg'},
    {name: 'PASEK', image: '/assets/compressed/item/pasek.jpeg'},
    {name: 'NÓŻ', image: '/assets/compressed/item/noz.jpeg'},
    {name: 'TROFEUM', image: '/assets/compressed/item/trofeum.jpeg'},
    {name: 'ZAŚNIEDZIAŁE MONETY', image: '/assets/compressed/item/zasniedziale_monety.jpeg'},
    {name: 'ŻYLETKA', image: '/assets/compressed/item/zyletka.jpeg'},
    {name: 'SZTUCZNA SZCZĘKA', image: '/assets/compressed/item/sztuczna_szczeka.jpeg'},
    {name: 'LIST', image: '/assets/compressed/item/list.jpeg'},
    {name: 'KAMIENIE SZLACHETNE', image: '/assets/compressed/item/kamienie_szlachetne.jpeg'},
    {name: 'TELEFON KOMÓRKOWY', image: '/assets/compressed/item/telefon_komorkowy.jpeg'},
    {name: 'SAMOCHÓD', image: '/assets/compressed/item/samochod.jpeg'},
    {name: 'GITARA', image: '/assets/compressed/item/gitara.jpeg'},
    {name: 'KAMIEN', image: '/assets/compressed/item/kamien.jpeg'},
    {name: 'ŁOPATA', image: '/assets/compressed/item/lopata.jpeg'},
    {name: 'NOŻYCZKI', image: '/assets/compressed/item/nozyczki.jpeg'},
    {name: 'PĘDZEL', image: '/assets/compressed/item/pedzel.jpeg'},
    {name: 'SIEKIERA', image: '/assets/compressed/item/siekiera.jpeg'},
    {name: 'SZNUR', image: '/assets/compressed/item/sznur.jpeg'},
    {name: 'BENZYNA W BUTELCE', image: '/assets/compressed/item/benzyna_w_butelce.jpeg'},
    {name: 'BRZYTWA', image: '/assets/compressed/item/brzytwa.jpeg'},
    {name: 'BUMERANG', image: '/assets/compressed/item/bumerang.jpeg'},
    {name: 'BUTELKA', image: '/assets/compressed/item/butelka.jpeg'},
    {name: 'CEGŁA', image: '/assets/compressed/item/cegla.jpeg'},
    {name: 'CHEMIKALIA', image: '/assets/compressed/item/chemikalia.jpeg'},
    {name: 'CHLOROFORM', image: '/assets/compressed/item/chloroform.jpeg'},
    {name: 'FIGURKA', image: '/assets/compressed/item/figurka.jpeg'},
    {name: 'GAŚNICA', image: '/assets/compressed/item/gasnica.jpeg'},
    {name: 'GAZ PIEPRZOWY', image: '/assets/compressed/item/gaz_pieprzowy.jpeg'},
    {name: 'GRZYBY', image: '/assets/compressed/item/grzyby.jpeg'},
    {name: 'GUMOWA PAŁKA', image: '/assets/compressed/item/gumowa_palka.jpeg'},
    {name: 'HANTEL', image: '/assets/compressed/item/hantel.jpeg'},
    {name: 'KABEL', image: '/assets/compressed/item/kabel.jpeg'},
    {name: 'KAJDANKI', image: '/assets/compressed/item/kajdanki.jpeg'},
    {name: 'KANISTER Z BENZYNĄ', image: '/assets/compressed/item/kanister_z_benzyna.jpeg'},
    {name: 'KASTET', image: '/assets/compressed/item/kastet.jpeg'},
    {name: 'KIJ GOLFOWY', image: '/assets/compressed/item/kij_golfowy.jpeg'},
    {name: 'KLUCZ DO KÓŁ', image: '/assets/compressed/item/klucz_do_kol.jpeg'},
    {name: 'KLUCZ FRANCUSKI', image: '/assets/compressed/item/klucz_francuski.jpeg'},
    {name: 'KORKOCIĄG', image: '/assets/compressed/item/korkociag.jpeg'},
    {name: 'KRAWAT', image: '/assets/compressed/item/krawat.jpeg'},
    {name: 'KULA BILARDOWA', image: '/assets/compressed/item/kula_bilardowa.jpeg'},
    {name: 'KUSZA', image: '/assets/compressed/item/kusza.jpeg'},
    {name: 'ŁAŃCUCH', image: '/assets/compressed/item/lancuch.jpeg'},
    {name: 'MACZETA', image: '/assets/compressed/item/maczeta.jpeg'},
    {name: 'METALOWA RURA', image: '/assets/compressed/item/metalowa_rura.jpeg'},
    {name: 'ODCISK PALCA', image: '/assets/compressed/item/odcisk_palca.jpeg'},
    {name: 'OPASKA UCISKOWA', image: '/assets/compressed/item/opaska_uciskowa.jpeg'},
    {name: 'PARASOLKA', image: '/assets/compressed/item/parasolka.jpeg'},
    {name: 'PATELNIA', image: '/assets/compressed/item/patelnia.jpeg'},
    {name: 'PENDRIVE', image: '/assets/compressed/item/pendrive.jpeg'},
    {name: 'PODUSZKA', image: '/assets/compressed/item/poduszka.jpeg'},
    {name: 'RÓŻANIEC', image: '/assets/compressed/item/rozaniec.jpeg'},
    {name: 'SEKATOR', image: '/assets/compressed/item/sekator.jpeg'},
    {name: 'SKALPEL', image: '/assets/compressed/item/skalpel.jpeg'},
    {name: 'ŚLAD BUTA', image: '/assets/compressed/item/slad_buta.jpeg'},
    {name: 'ŚWIECZNIK', image: '/assets/compressed/item/swiecznik.jpeg'},
    {name: 'SZPIKULEC DO LODU', image: '/assets/compressed/item/szpikulec_do_lodu.jpeg'},
    {name: 'WIDŁY', image: '/assets/compressed/item/widly.jpeg'},
    {name: 'ZAPALNICZKA', image: '/assets/compressed/item/zapalniczka.jpeg'},
    {name: 'ZDJĘCIE', image: '/assets/compressed/item/zdjecie.jpeg'},
    {name: 'ZEGAREK', image: '/assets/compressed/item/zegarek.jpeg'},
    {name: 'ŻELAZKO', image: '/assets/compressed/item/zelazko.jpeg'},
    {name: 'ZSZYWACZ', image: '/assets/compressed/item/zszywacz.jpeg'},
  ],

MOTIVE: [
    {name: 'NIEUDANA OPERACJA PLASTYCZNA', image: '/assets/compressed/motive/nieudana_operacja_plastyczna.jpeg'},
    {name: 'UPUBLICZNIENIE PRYWATNYCH ZDJĘĆ', image: '/assets/compressed/motive/upublicznienie_prywatnych_zdjec.jpeg'},
    {name: 'SAMOTNOŚĆ', image: '/assets/compressed/motive/samotnosc.jpeg'},
    {name: 'SAMOOBRONA', image: '/assets/compressed/motive/samoobrona.jpeg'},
    {name: 'ZDRADA', image: '/assets/compressed/motive/zdrada.jpeg'},
    {name: 'ZNĘCANIE SIĘ', image: '/assets/compressed/motive/znecanie_sie.jpeg'},
    {name: 'CIĄŻA', image: '/assets/compressed/motive/ciaza.jpeg'},
    {name: 'UTRATA PRACY', image: '/assets/compressed/motive/utrata_pracy.jpeg'},
    {name: 'ZBIEG OKOLICZNOŚCI', image: '/assets/compressed/motive/zbieg_okolicznosci.jpeg'},
    {name: 'KRYZYS WIEKU ŚREDNIEGO', image: '/assets/compressed/motive/kryzys_wieku_sredniego.jpeg'},
    {name: 'BIZNES NA BOKU', image: '/assets/compressed/motive/biznes_na_boku.jpeg'},
    {name: 'ROMANS', image: '/assets/compressed/motive/romans.jpeg'},
    {name: 'DŁUG', image: '/assets/compressed/motive/dlug.jpeg'},
    {name: 'ZŁAMANE SERCE', image: '/assets/compressed/motive/zlamane_serce.jpeg'},
    {name: 'KŁAMSTWO', image: '/assets/compressed/motive/klamstwo.jpeg'},
    {name: 'SPADEK', image: '/assets/compressed/motive/spadek.jpeg'},
    {name: 'PRANIE MÓZGU', image: '/assets/compressed/motive/pranie_mozgu.jpeg'},
    {name: 'NIESPRAWIEDLIWOŚĆ', image: '/assets/compressed/motive/niesprawiedliwosc.jpeg'},
    {name: 'ZEMSTA', image: '/assets/compressed/motive/zemsta.jpeg'},
    {name: 'NARKOTYKI', image: '/assets/compressed/motive/narkotyki.jpeg'},
    {name: 'PLOTKA', image: '/assets/compressed/motive/plotka.jpeg'},
    {name: 'ZAZDROŚĆ', image: '/assets/compressed/motive/zazdrosc.jpeg'},
    {name: 'TAJEMNICA Z PRZESZŁOŚCI', image: '/assets/compressed/motive/tajemnica_z_przeszlosci.jpeg'},
    {name: 'UPRZEDZENIE', image: '/assets/compressed/motive/uprzedzenie.jpeg'},
    {name: 'NIENAWIŚĆ', image: '/assets/compressed/motive/nienawisc.jpeg'},
    {name: 'KORZYŚCI MAJĄTKOWE', image: '/assets/compressed/motive/korzysci_majatkowe.jpeg'},
    {name: 'NIETRZEŹWOŚĆ', image: '/assets/compressed/motive/nietrzezwosc.jpeg'},
    {name: 'POPĘD SEKSUALNY', image: '/assets/compressed/motive/poped_seksualny.jpeg'},
    {name: 'PROBLEMY PSYCHICZNE', image: '/assets/compressed/motive/problemy_psychiczne.jpeg'},
    {name: 'CHCIWOŚĆ', image: '/assets/compressed/motive/chciwosc.jpeg'},
    {name: 'AMBICJA', image: '/assets/compressed/motive/ambicja.jpeg'},
    {name: 'DESPERACJA', image: '/assets/compressed/motive/desperacja.jpeg'},
    {name: 'FANATYZM RELIGIJNY', image: '/assets/compressed/motive/fanatyzm_religijny.jpeg'},
    {name: 'NIEULECZALNA CHOROBA', image: '/assets/compressed/motive/nieuleczalna_choroba.jpeg'},
    {name: 'OBSESJA', image: '/assets/compressed/motive/obsesja.jpeg'},
    {name: 'PORZUCENIE', image: '/assets/compressed/motive/porzucenie.jpeg'},
    {name: 'STRACH', image: '/assets/compressed/motive/strach.jpeg'},
    {name: 'SZANTAŻ', image: '/assets/compressed/motive/szantaz.jpeg'},
    {name: 'UKRYTA TOŻSAMOŚĆ', image: '/assets/compressed/motive/ukryta_tozsamosc.jpeg'},
    {name: 'UPOKORZENIE', image: '/assets/compressed/motive/upokorzenie.jpeg'},
    {name: 'UTRATA DZIECKA', image: '/assets/compressed/motive/utrata_dziecka.jpeg'},
    {name: 'WŁADZA', image: '/assets/compressed/motive/wladza.jpeg'},
    {name: 'WYPADEK', image: '/assets/compressed/motive/wypadek.jpeg'},
    {name: 'CHWILA SZALEŃSTWA', image: '/assets/compressed/motive/chwila_szalenstwa.jpeg'},
    {name: 'FAŁSZYWE OSKARŻENIE', image: '/assets/compressed/motive/falszywe_oskarzenie.jpeg'},
    {name: 'HAZARD', image: '/assets/compressed/motive/hazard.jpeg'},
    {name: 'IDEOLOGIA', image: '/assets/compressed/motive/ideologia.jpeg'},
    {name: 'KORUPCJA', image: '/assets/compressed/motive/korupcja.jpeg'},
    {name: 'NARCYZM', image: '/assets/compressed/motive/narcyzm.jpeg'},
    {name: 'NIEŚLUBNE DZIECKO', image: '/assets/compressed/motive/nieslubne_dziecko.jpeg'},
    {name: 'OCHRONA TAJEMNICY', image: '/assets/compressed/motive/ochrona_tajemnicy.jpeg'},
    {name: 'ODRZUCENIE', image: '/assets/compressed/motive/odrzucenie.jpeg'},
    {name: 'PARANOJA', image: '/assets/compressed/motive/paranoja.jpeg'},
    {name: 'POCZUCIE WINY', image: '/assets/compressed/motive/poczucie_winy.jpeg'},
    {name: 'PRZYPADEK', image: '/assets/compressed/motive/przypadek.jpeg'},
    {name: 'TRAUMA', image: '/assets/compressed/motive/trauma.jpeg'},
    {name: 'WSTYD', image: '/assets/compressed/motive/wstyd.jpeg'},
  ],
}

// todo:
// SAUNA
// - JACHT                                                                                                                                                                                    
//   - ZAKŁAD POGRZEBOWY                                                                                                                                                                        
//   - SZKLARNIA                                                                                                                                                                                
//   - FABRYKA                                                                                                                                                                       
//   - KANAŁY                                                                                                                                                                                   
//   - BALKON            
//   - WINIARNIA
//   - TAKSÓWKA